### ISSUE TITLE
Enhancement: Add compound address string to API response

### ISSUE THREAD

**Issue by omega1x** [lll-phill-lll/address_correction#1]
Add field **StandardAddressString**  to [Response struct](https://github.com/lll-phill-lll/address_correction/blob/aab5ec730df389ffb090573d652d67bcebe266bd/api/model.go#L18). 

The **StandardAddressString** field should be a concatenation of the next fields of **CorrectAddress struct**:
- City
- StreetType
- SreetName
- HouseNumber
- Korpus 

delimited with comma.

**Comment by lll-phill-lll** [comment]
fixed in https://github.com/lll-phill-lll/address_correction/releases/tag/2.0
