### ISSUE TITLE
Enhancement: Rename binary and configuration files

### ISSUE THREAD

**Issue by omega1x** [lll-phill-lll/address_correction#2]
Make names of [binary](https://github.com/lll-phill-lll/address_correction/blob/master/binary/linux) and [configuration file](https://github.com/lll-phill-lll/address_correction/blob/master/binary/config.yaml) shorter. The name of [configuration file](https://github.com/lll-phill-lll/address_correction/blob/master/binary/config.yaml) should contain the name of [binary](https://github.com/lll-phill-lll/address_correction/blob/master/binary/linux) file.

**Comment by lll-phill-lll** [comment]
Fixed in https://github.com/lll-phill-lll/address_correction/releases/tag/2.0
